
discovery.zen.ping.multicast.enabled: true


path:
  data: /data/
  repo: /backups
  work: /data/work
  logs: /logs
  repo: ["/backups"]


shield:
  authc:
    realms:
      file1:
        type: esusers
        order: 1
      native1:
        type: native
        order: 0


script:
  inline: on
  indexed: on



http:
  cors.enabled: false


marvel.agent.exporters:
  id1:
    type: http
    host: ["http://marvel:9200"]
    auth:
      username: es_admin
      password: password


  
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.query.debug: 2s
index.search.slowlog.threshold.query.trace: 500ms

index.search.slowlog.threshold.fetch.warn: 1s
index.search.slowlog.threshold.fetch.info: 800ms
index.search.slowlog.threshold.fetch.debug: 500ms
index.search.slowlog.threshold.fetch.trace: 200ms

