
# The Elasticsearch instance to use for all your queries.
# uncomment followinf line first time u run so it will create .kibana
elasticsearch_url: "http://es1:9200"

# If your Elasticsearch is protected with basic auth, this is the user credentials
# used by the Kibana server to perform maintence on the kibana_index at statup. Your Kibana
# users will still need to authenticate with Elasticsearch (which is proxied thorugh
# the Kibana server)
kibana_elasticsearch_username: "kibana4-server"
kibana_elasticsearch_password: "password"

#marvel.node_resolver: name

verify_ssl: true
server.ssl.key: /config/kibana.key
server.ssl.cert: /config/kibana.crt


shield.encryptionKey: "something_secret"
shield.sessionTimeout: 600000

